from generators.engineering_knowledge_update_service import (
    EngineeringKnowledgeUpdateService,
)
from models.requests import CurrentEngineeringKnowledge
from models.response import SuggestedUpdate


class EngineeringKnowledgeApprovalService:
    """
    Applies only user-approved engineering knowledge updates.

    Suggestions are generated by the analysis pipeline, but they are
    not considered applied until explicitly supplied as approved updates.
    """

    def __init__(
        self,
        update_service: EngineeringKnowledgeUpdateService,
    ) -> None:
        self._update_service = update_service

    def apply_approved_updates(
        self,
        knowledge: CurrentEngineeringKnowledge,
        suggested_updates: list[SuggestedUpdate],
        approved_updates: list[SuggestedUpdate],
    ) -> CurrentEngineeringKnowledge:
        self._validate_approved_updates(
            suggested_updates=suggested_updates,
            approved_updates=approved_updates,
        )

        if not approved_updates:
            return knowledge.model_copy(deep=True)

        return self._update_service.apply_updates(
            knowledge=knowledge,
            updates=approved_updates,
        )

    def _validate_approved_updates(
        self,
        suggested_updates: list[SuggestedUpdate],
        approved_updates: list[SuggestedUpdate],
    ) -> None:
        for approved_update in approved_updates:
            if not any(
                self._updates_match(approved_update, suggested_update)
                for suggested_update in suggested_updates
            ):
                raise ValueError(
                    "An approved update was not present in the generated "
                    "suggested updates."
                )

    @staticmethod
    def _updates_match(
        first: SuggestedUpdate,
        second: SuggestedUpdate,
    ) -> bool:
        return (
            first.artifactType == second.artifactType
            and first.artifactPath == second.artifactPath
            and first.changeType == second.changeType
            and first.section == second.section
            and first.currentContent == second.currentContent
            and first.suggestedContent == second.suggestedContent
            and first.explanation == second.explanation
            and first.confidence == second.confidence
        )